use_frameworks!

platform :ios, '10.0'

target 'WeCloudIosSdk_Example' do
  pod 'WeCloudIosSdk', :path => '../'

  target 'WeCloudIosSdk_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
